// <auto-generated />
namespace GreenSol.Domain.EFDbContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmailProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201711171337496_EmailProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
